In [1]:
import numpy as np
import random

def crear_tablero() -> np.ndarray:
    """
    Crea un tablero de 5x5 lleno de ceros (agua) y coloca 3 barcos (unos)
    en posiciones aleatorias sin repetirse.

    Returns:
        np.ndarray: Matriz de NumPy de 5x5 que representa el tablero.
    """
    # Paso 1: Crear una matriz de 5x5 llena de ceros
    tablero = np.zeros((5, 5), dtype=int)

    # Paso 2: Colocar 3 barcos en posiciones aleatorias
    barcos_colocados = 0
    while barcos_colocados < 3:
        # Generar una fila y columna aleatoria entre 0 y 4
        fila = random.randint(0, 4)
        columna = random.randint(0, 4)

        # Verificar si la celda ya tiene un barco (para no encimarlos)
        if tablero[fila, columna] == 0:
            tablero[fila, columna] = 1
            barcos_colocados += 1

    return tablero


def verificar_disparo(tablero: np.ndarray, x: int, y: int):
    """
    Verifica si las coordenadas dadas golpean un barco o caen al agua.

    Args:
        tablero (np.ndarray): El tablero de juego actual.
        x (int): Coordenada de la fila (0 a 4).
        y (int): Coordenada de la columna (0 a 4).
    """
    # Validación de seguridad: asegurarse de que el disparo esté dentro del tablero
    if not (0 <= x < 5 and 0 <= y < 5):
        print(f"❌ ¡Coordenadas fuera de rango! ({x}, {y}) no es un disparo válido (usa números de 0 a 4).")
        return

    # Verificar qué hay en la posición seleccionada
    if tablero[x, y] == 1:
        print(f"💥 ¡TOCADO! Un barco enemigo fue destruido en la posición ({x}, {y}).")
        # Opcional: Podrías cambiar el 1 por un -1 o un 0 para hundirlo,
        # pero el desafío solo pide verificar.
    else:
        print(f"🌊 ¡AGUA! El disparo en ({x}, {y}) cayó al mar.")


def main():
    print("--- Desafío 25: Batalla Naval (NumPy) --- \n")

    # 1. Inicializar el tablero con los barcos aleatorios
    tablero_juego = crear_tablero()

    # Nota trampa para el programador (para poder probar el código):
    # En un juego real ocultarías esto, pero aquí lo imprimimos para verificar.
    print("🤖 [Vista del Servidor/Trampa] Tablero generado:")
    print(tablero_juego)
    print("\n-----------------------------------------\n")

    # 2. Simulación de disparos por parte del usuario
    print("Simulando disparos del jugador:")

    # Disparo de prueba 1
    print("\nDisparo 1: Apuntando a (2, 3)")
    verificar_disparo(tablero_juego, 2, 3)

    # Disparo de prueba 2
    print("\nDisparo 2: Apuntando a (0, 0)")
    verificar_disparo(tablero_juego, 0, 0)

    # Disparo de prueba 3 (Buscamos un barco de la matriz impresa arriba para asegurar un acierto)
    # Vamos a buscar dinámicamente las coordenadas de un barco para la demostración
    coordenadas_barcos = np.argwhere(tablero_juego == 1)
    fila_barco, col_barco = coordenadas_barcos[0]

    print(f"\nDisparo 3: Apuntando a un barco conocido en ({fila_barco}, {col_barco})")
    verificar_disparo(tablero_juego, fila_barco, col_barco)


if __name__ == "__main__":
    main()

--- Desafío 25: Batalla Naval (NumPy) --- 

🤖 [Vista del Servidor/Trampa] Tablero generado:
[[0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 1 0 0]]

-----------------------------------------

Simulando disparos del jugador:

Disparo 1: Apuntando a (2, 3)
💥 ¡TOCADO! Un barco enemigo fue destruido en la posición (2, 3).

Disparo 2: Apuntando a (0, 0)
🌊 ¡AGUA! El disparo en (0, 0) cayó al mar.

Disparo 3: Apuntando a un barco conocido en (0, 1)
💥 ¡TOCADO! Un barco enemigo fue destruido en la posición (0, 1).
